<?php

namespace App\Console\Commands;

use App\Services\Accounting\LedgerPoster;
use App\Support\Modules;
use App\Support\PropertyIsolation;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

/**
 * Regenerates the "how big is this system, and what is covered" census that
 * docs/PROJECT-MAP.md embeds, by MEASURING the codebase rather than trusting prose.
 *
 * WHY THIS EXISTS. PROJECT-MAP.md was hand-written on 2026-06-29 and claimed 28 models /
 * 18 admin resources / 20 module docs / 220 test files. Three weeks later the real numbers
 * were 61 / 36 / 27 / 313 — the project had roughly doubled and the map that was supposed
 * to orient the team described a system that no longer existed. A map you have to remember
 * to update is a map that is wrong; this one is generated.
 *
 * Run it after adding a module (or any time the shape changes):
 *     php artisan atriom:dump-system-census
 *
 * It rewrites the block between the census markers in docs/PROJECT-MAP.md and writes the
 * same facts to docs/system-census.json for anything else that wants them.
 */
class DumpSystemCensus extends Command
{
    protected $signature = 'atriom:dump-system-census
        {--check : Exit non-zero if the embedded census is stale instead of rewriting it}';

    protected $description = 'Measure the codebase and regenerate the census block in docs/PROJECT-MAP.md';

    public const JSON_PATH = 'docs/system-census.json';

    public const MAP_PATH = 'docs/PROJECT-MAP.md';

    private const MARKER_START = '<!-- census:start — generated by `php artisan atriom:dump-system-census`; do not hand-edit -->';

    private const MARKER_END = '<!-- census:end -->';

    public function handle(): int
    {
        $census = static::census();
        $json = json_encode($census, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE).PHP_EOL;
        $block = self::MARKER_START."\n\n".$this->render($census)."\n".self::MARKER_END;

        $mapPath = base_path(self::MAP_PATH);
        $map = is_file($mapPath) ? file_get_contents($mapPath) : '';

        if (! str_contains($map, self::MARKER_START) || ! str_contains($map, self::MARKER_END)) {
            $this->error(self::MAP_PATH.' has no census markers — add them where the census should render.');

            return self::FAILURE;
        }

        $rewritten = preg_replace(
            '/'.preg_quote(self::MARKER_START, '/').'.*?'.preg_quote(self::MARKER_END, '/').'/s',
            $block,
            $map,
        );

        if ($this->option('check')) {
            $stale = trim($rewritten) !== trim($map);
            if ($stale) {
                $this->error(self::MAP_PATH.' census is stale — run `php artisan atriom:dump-system-census`.');

                return self::FAILURE;
            }
            $this->info('Census is up to date.');

            return self::SUCCESS;
        }

        file_put_contents($mapPath, $rewritten);
        file_put_contents(base_path(self::JSON_PATH), $json);

        $this->info('Census written to '.self::MAP_PATH.' + '.self::JSON_PATH);
        $this->table(['metric', 'count'], [
            ['models', $census['codebase']['models']],
            ['services', $census['codebase']['services']],
            ['admin resources', $census['codebase']['admin_resources']],
            ['module docs', $census['modules']['documented']],
            ['test files', $census['tests']['files']],
            ['GL posting sources', $census['coverage']['gl_sources']],
        ]);

        return self::SUCCESS;
    }

    /** Measure everything. Shared with the docs so both compute identically. */
    public static function census(): array
    {
        return [
            'generated_note' => 'Generated by `php artisan atriom:dump-system-census`. Do not hand-edit.',
            'codebase' => [
                'models' => self::countPhp('app/Models'),
                'services' => self::countPhp('app/Services', recursive: true),
                'admin_resources' => count(self::dirs('app/Filament/Admin/Resources')),
                'portal_resources' => count(self::dirs('app/Filament/Portal/Resources')),
                'admin_widgets' => self::countPhp('app/Filament/Admin/Widgets'),
                'api_controllers' => self::countPhp('app/Http/Controllers/Api/V1', recursive: true),
                'console_commands' => self::countPhp('app/Console/Commands'),
                'jobs' => self::countPhp('app/Jobs'),
                'notifications' => self::countPhp('app/Notifications'),
                'migrations' => self::countPhp('database/migrations'),
            ],
            'modules' => self::modules(),
            'coverage' => [
                'gl_sources' => count(LedgerPoster::sources()),
                // Concrete journalizer classes on disk. Should equal gl_sources — a surplus
                // means a journalizer exists but is registered nowhere, which is exactly how
                // the SlaPenalty posting bug hid. GlRegistryConformanceTest gates it.
                'gl_journalizer_files' => count(array_filter(
                    self::files('app/Services/Accounting/Journalizers', '*Journalizer.php'),
                    fn ($f) => basename($f) !== 'Journalizer.php',
                )),
                'property_isolation' => [
                    'owned' => count(PropertyIsolation::ownedModels()),
                    'shared' => count(PropertyIsolation::sharedModels()),
                    'self' => count(PropertyIsolation::selfModels()),
                ],
                'module_flags' => count(Modules::KEYS),
                'scheduled_commands' => self::scheduled(),
            ],
            'tests' => [
                'files' => self::countFiles('tests', '*Test.php'),
                'e2e_specs' => self::countFiles('tests/e2e', '*.spec.js'),
                'scenarios' => self::countFiles('tests/Feature/Scenarios', '*Test.php'),
                'regressions' => self::countFiles('tests/Feature/Regression', '*Test.php'),
            ],
        ];
    }

    /**
     * The module docs.
     *
     * This used to also report which modules had ever been gap-analysed, by counting
     * `docs/gap-analysis/NN-*.md` files. That metric existed to surface ONE hole — modules
     * 21-27 were built after round 1 and had never been audited — and round 3 closed it on
     * 2026-08-18 by analysing all 37. The gap analysis is now a single living document
     * (`docs/gap-analysis/README.md`) rather than a file per module, so counting files would
     * report 0 of 37 and read as a catastrophic regression of a hole that no longer exists.
     * A metric whose question has been answered is worse than no metric: it goes on being
     * measured, and the number it prints is about the shape of a directory rather than about
     * the codebase.
     */
    private static function modules(): array
    {
        $docs = self::files('docs/modules', '*.md');

        $modules = [];
        foreach ($docs as $file) {
            if (! preg_match('/^(\d{2})-(.+)\.md$/', basename($file), $m)) {
                continue;
            }
            $number = (int) $m[1];
            $modules[] = [
                'number' => $number,
                'slug' => $m[2],
                'title' => Str::of($m[2])->replace('-', ' ')->title()->toString(),
                'doc' => 'docs/modules/'.basename($file),
            ];
        }
        usort($modules, fn ($a, $b) => $a['number'] <=> $b['number']);

        return [
            'documented' => count($modules),
            'list' => $modules,
        ];
    }

    /**
     * Commands the scheduler actually runs. Reads routes/console.php rather than booting the
     * schedule, and counts Schedule::job(...) too — billing:run-monthly and
     * billing:apply-late-fees are registered as JOBS, so a naive Schedule::command() grep
     * reports them as unscheduled.
     */
    private static function scheduled(): array
    {
        $source = is_file(base_path('routes/console.php')) ? file_get_contents(base_path('routes/console.php')) : '';

        preg_match_all("/Schedule::command\(\s*'([^']+)'/", $source, $commands);
        preg_match_all('/Schedule::job\(\s*new\s+([A-Za-z0-9_\\\\]+)/', $source, $jobs);

        // preg_match_all always populates capture-group offset 1 (empty on no match), so no `??`.
        return [
            'commands' => array_values(array_unique($commands[1])),
            'jobs' => array_values(array_unique(array_map('class_basename', $jobs[1]))),
        ];
    }

    private function render(array $c): string
    {
        $cb = $c['codebase'];
        $cov = $c['coverage'];
        $t = $c['tests'];
        $m = $c['modules'];

        $pi = $cov['property_isolation'];
        $classified = $pi['owned'] + $pi['shared'] + $pi['self'];

        $lines = [];
        $lines[] = '### Scale of the codebase';
        $lines[] = '';
        $lines[] = '| | | | |';
        $lines[] = '|---|---|---|---|';
        $lines[] = "| **{$cb['models']}** models | **{$cb['services']}** services | **{$cb['admin_resources']}** admin resources | **{$cb['portal_resources']}** portal resources |";
        $lines[] = "| **{$cb['api_controllers']}** API controllers | **{$cb['admin_widgets']}** dashboard widgets | **{$cb['console_commands']}** console commands | **{$cb['jobs']}** queued jobs |";
        $lines[] = "| **{$cb['notifications']}** notifications | **{$cb['migrations']}** migrations | **{$m['documented']}** module docs | **{$t['files']}** test files |";
        $lines[] = '';
        $lines[] = '### Coverage — what the gates actually enforce';
        $lines[] = '';
        $lines[] = '| Dimension | State |';
        $lines[] = '|---|---|';
        $lines[] = "| **Property isolation** | {$classified} models classified — {$pi['owned']} property-owned, {$pi['shared']} shared, {$pi['self']} self. Gated by `PropertyIsolationConformanceTest`. |";
        $lines[] = "| **General ledger** | {$cov['gl_sources']} posting sources, {$cov['gl_journalizer_files']} journalizer classes — every one registered. One registry (`LedgerPoster::JOURNALIZERS`) that all four dispatch paths derive from; gated by `GlRegistryConformanceTest`. |";
        $lines[] = "| **E2E smoke** | Every admin resource + page, from `tests/e2e/filament-admin-manifest.json`; {$t['e2e_specs']} specs. Gated by `AdminSmokeManifestConformanceTest`. |";
        $lines[] = "| **Tests** | {$t['files']} files — {$t['scenarios']} scenario, {$t['regressions']} regression. |";
        $lines[] = "| **Module flags** | {$cov['module_flags']} toggleable modules (`App\\Support\\Modules`). |";
        $lines[] = '';
        $lines[] = '**Scheduled automation** — commands: `'.implode('` · `', $cov['scheduled_commands']['commands']).'`';
        if ($cov['scheduled_commands']['jobs']) {
            $lines[] = '; jobs: `'.implode('` · `', $cov['scheduled_commands']['jobs']).'` (registered via `Schedule::job`, so they do **not** appear as scheduled commands).';
        }
        $lines[] = '';
        $lines[] = '### Module documentation';
        $lines[] = '';
        $lines[] = "**{$m['documented']}** modules carry a doc in [`docs/modules/`](modules/). Every one of them has been gap-analysed at least once; the standing verdict per module lives in [`docs/gap-analysis/`](gap-analysis/README.md), which is one living document rather than a file per module.";

        return implode("\n", $lines)."\n";
    }

    private static function dirs(string $relative): array
    {
        $path = base_path($relative);

        return is_dir($path) ? File::directories($path) : [];
    }

    /** @return array<int, string> absolute paths of files directly under $relative matching $pattern */
    private static function files(string $relative, string $pattern): array
    {
        $path = base_path($relative);

        return is_dir($path) ? (File::glob($path.'/'.$pattern) ?: []) : [];
    }

    private static function countFiles(string $relative, string $pattern): int
    {
        $path = base_path($relative);
        if (! is_dir($path)) {
            return 0;
        }

        return count(array_filter(
            iterator_to_array(File::allFiles($path)),
            fn ($f) => fnmatch($pattern, $f->getFilename()),
        ));
    }

    private static function countPhp(string $relative, bool $recursive = false): int
    {
        $path = base_path($relative);
        if (! is_dir($path)) {
            return 0;
        }

        $files = $recursive ? File::allFiles($path) : File::files($path);

        return count(array_filter($files, fn ($f) => $f->getExtension() === 'php'));
    }
}
