import DefaultTheme from 'vitepress/theme'
import type { Theme } from 'vitepress'
import './custom.css'

import PostingExplorer from './components/PostingExplorer.vue'
import StateMachine from './components/StateMachine.vue'
import PercentageRentCalculator from './components/PercentageRentCalculator.vue'
import VatRateResolver from './components/VatRateResolver.vue'

// Default VitePress theme (clean, searchable chrome) + Atriom's warm sand/teal identity, the
// "picture" components (flow, lifecycle pills, T-account cards), and the interactive ones below.
//
// Registered GLOBALLY rather than imported per page: they are used across both locales and a dozen
// pages, and a missing import in one Arabic page renders the tag as literal text rather than
// failing the build — silent, and invisible to whoever does not read that language.
//
// Two kinds live here, and the difference matters:
//   - DERIVED (PostingExplorer, StateMachine) read `.vitepress/data/*.json`, regenerated by
//     `php artisan atriom:dump-handbook-data` from the code's own registries. They cannot describe
//     a system that does not exist, and a conformance test fails the build if the dump goes stale.
//   - ILLUSTRATIVE (the calculators) mirror one small rule each so a reader can change a number and
//     watch the answer move. Each names the class it mirrors and says that class is the authority.
//     They are kept to rules that are a single line of arithmetic, so the copy has no room to drift
//     into a second opinion.
export default {
  extends: DefaultTheme,
  enhanceApp({ app }) {
    app.component('PostingExplorer', PostingExplorer)
    app.component('StateMachine', StateMachine)
    app.component('PercentageRentCalculator', PercentageRentCalculator)
    app.component('VatRateResolver', VatRateResolver)
  },
} satisfies Theme
