<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * `charges.origin` — where a schedule row came from.
 *
 * A lease's rent stops being ONE mutable row and becomes a date-ranged schedule: a rent change
 * closes the current row and opens the next rather than overwriting the amount, so what the rent
 * WAS stays readable and what it WILL BE is visible before it bills (Yardi's model —
 * docs/benchmarks/yardi/01-yardi-lease-administration.md §3.2, story LS-01/LS-03).
 *
 * Once there can be several rows per charge type, "why does this lease have four rent rows" needs
 * an answer that is data rather than archaeology. Every row records whether it was seeded at
 * creation, typed by an operator, generated by the escalation sweep, or carried over on renewal.
 *
 * Backfilled as `seed` for everything that exists today: those rows were created by
 * LeaseCreationService/LeaseRenewalService/MarketingLevyService before schedules existed, and
 * calling them `manual` would claim an operator typed them.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('charges', function (Blueprint $table) {
            $table->string('origin', 24)->default('seed')->after('type');
        });

        // Existing rows keep the default; make it explicit so a later default change can't
        // silently re-label history.
        \Illuminate\Support\Facades\DB::table('charges')->update(['origin' => 'seed']);
    }

    public function down(): void
    {
        Schema::table('charges', function (Blueprint $table) {
            $table->dropColumn('origin');
        });
    }
};
